In [1]:
#Importación de librerias útiles
import pandas
corpus_filtro3 = pandas.read_csv("corpus_filtro3.csv",encoding='utf-8')

#Librerias cientificas scipy, numpy
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import time
import math

#Lectura de archivos xml
from lxml import etree

#Expresiones regulares
import re

#Pyfreeling
from pyfreeling import Analyzer
analyzer = Analyzer(config='/usr/share/freeling/config/es.cfg', lang='es')

#Para aplicar Naive Bayes
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import metrics
vectorizer = CountVectorizer(stop_words='english')

# Calculo de la mediana

In [23]:
text_list=corpus_filtro3['text'][:]
category_list=corpus_filtro3['category'][:]
h1_list=corpus_filtro3['1'][:]
h2_list=corpus_filtro3['2'][:]
h3_list=corpus_filtro3['3'][:]
h4_list=corpus_filtro3['4'][:]
h5_list=corpus_filtro3['5'][:]
medians=[]
pos=0
for i in range( len(corpus_filtro3)):
    values = []
    for j in range( h1_list[i]):
        values.append(1)
    for j in range( h2_list[i] ):
        values.append(2)
    for j in range( h3_list[i] ):
        values.append(3)
    for j in range( h4_list[i] ):
        values.append(4)
    for j in range( h5_list[i] ):
        values.append(5)
    if len(values) == 0:
        values.append(0)  
    mediana=np.median(values)
    if( len(values) % 2 == 1 ):
        medians.append(math.floor(mediana))
    else:
        for i in values:
            if( i >= mediana):
                medians.append(i)
                break
    pos+=1
        
print(len(medians), " ", len(corpus_filtro3))

3438   3438


In [24]:
print("Agregando informacion de mediana")
d = {'text' : corpus_filtro3['text'][:],
    'category' : corpus_filtro3['category'][:],
    'median': medians,
    '1':corpus_filtro3['1'][:],
    '2':corpus_filtro3['2'][:],
    '3':corpus_filtro3['3'][:],
    '4':corpus_filtro3['4'][:],
    '5':corpus_filtro3['5'][:]
    }
df = pandas.DataFrame(d, columns = ['text', 'category', 'median', '1', '2', '3', '4', '5'])
df.to_csv('corpus_filtro4median.csv')
print("Tweets guardados en corpus_filtro4median.csv")

Agregando informacion de mediana
Tweets guardados en corpus_filtro4median.csv


# Clasificador 1 mediana con valor 1 o no

In [25]:
vectorizer_c1 = CountVectorizer(stop_words='english')

In [26]:
corpus_filtro4median = pandas.read_csv("corpus_filtro4median.csv",encoding='utf-8')
text_list_c1=corpus_filtro4median['text'][:]
median_list_c1=corpus_filtro4median['median'][:]
category_list_c1=[]
for i in median_list_c1:
    if(i == 1):
        category_list_c1.append(1)
    else:
        category_list_c1.append(0)

train_features_c1 = vectorizer.fit_transform(text_list_c1[:100])

In [27]:
#corpus_filtro5_devset = pandas.read_csv("corpus_filtro5_devset.csv",encoding='utf-8')
text_devlist_c1=corpus_filtro4median['text'][600:605]
#category_devlist=corpus_filtro5_devset['category'][:]
test_features_c1 = vectorizer.transform(text_devlist_c1)


In [28]:
nb_c1 = MultinomialNB()
nb_c1.fit(train_features_c1 , category_list_c1[:100])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
from sklearn.naive_bayes import MultinomialNB
nb_c1.predict_proba(test_features_c1)

array([[  9.53241233e-01,   4.67587673e-02],
       [  9.99903675e-01,   9.63250486e-05],
       [  9.86859572e-01,   1.31404276e-02],
       [  9.99815379e-01,   1.84620725e-04],
       [  9.99895555e-01,   1.04445411e-04]])

In [30]:
nb_c1.predict(test_features_c1)

array([0, 0, 0, 0, 0])

# Clasificador 2 mediana con valor 2 o no

In [31]:
vectorizer_c2 = CountVectorizer(stop_words='english')

In [32]:
#corpus_filtro4median = pandas.read_csv("corpus_filtro4median.csv",encoding='utf-8')
#text_list_c1=corpus_filtro4median['text'][:]
#median_list_c1=corpus_filtro4median['median'][:]
category_list_c2=[]
for i in median_list_c1:
    if(i == 2):
        category_list_c2.append(1)
    else:
        category_list_c2.append(0)

#train_features_c2 = vectorizer.fit_transform(text_list_c1[:100])

In [27]:
#corpus_filtro5_devset = pandas.read_csv("corpus_filtro5_devset.csv",encoding='utf-8')
#text_devlist_c1=corpus_filtro4median['text'][600:605]
#category_devlist=corpus_filtro5_devset['category'][:]
#test_features_c1 = vectorizer.transform(text_devlist_c1)


In [33]:
nb_c2 = MultinomialNB()
nb_c2.fit(train_features_c1 , category_list_c2[:100])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
from sklearn.naive_bayes import MultinomialNB
nb_c2.predict_proba(test_features_c1)

array([[  9.35809651e-01,   6.41903489e-02],
       [  9.99973222e-01,   2.67775706e-05],
       [  9.99315319e-01,   6.84681267e-04],
       [  9.99954818e-01,   4.51820711e-05],
       [  9.99930617e-01,   6.93832562e-05]])

In [35]:
nb_c2.predict(test_features_c1)

array([0, 0, 0, 0, 0])

# Clasificador 3 mediana con valor 3 o no

In [36]:
vectorizer_c3 = CountVectorizer(stop_words='english')

In [37]:
#corpus_filtro4median = pandas.read_csv("corpus_filtro4median.csv",encoding='utf-8')
#text_list_c1=corpus_filtro4median['text'][:]
#median_list_c1=corpus_filtro4median['median'][:]
category_list_c3=[]
for i in median_list_c1:
    if(i == 3):
        category_list_c3.append(1)
    else:
        category_list_c3.append(0)

#train_features_c2 = vectorizer.fit_transform(text_list_c1[:100])

In [27]:
#corpus_filtro5_devset = pandas.read_csv("corpus_filtro5_devset.csv",encoding='utf-8')
#text_devlist_c1=corpus_filtro4median['text'][600:605]
#category_devlist=corpus_filtro5_devset['category'][:]
#test_features_c1 = vectorizer.transform(text_devlist_c1)


In [38]:
nb_c3 = MultinomialNB()
nb_c3.fit(train_features_c1 , category_list_c3[:100])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [39]:
from sklearn.naive_bayes import MultinomialNB
nb_c3.predict_proba(test_features_c1)

array([[ 0.82353676,  0.17646324],
       [ 0.99702592,  0.00297408],
       [ 0.99072811,  0.00927189],
       [ 0.93235037,  0.06764963],
       [ 0.9873813 ,  0.0126187 ]])

In [40]:
nb_c3.predict(test_features_c1)

array([0, 0, 0, 0, 0])

# Clasificador 4 mediana con valor 4 o no

In [41]:
vectorizer_c4 = CountVectorizer(stop_words='english')

In [42]:
#corpus_filtro4median = pandas.read_csv("corpus_filtro4median.csv",encoding='utf-8')
#text_list_c1=corpus_filtro4median['text'][:]
#median_list_c1=corpus_filtro4median['median'][:]
category_list_c4=[]
for i in median_list_c1:
    if(i == 4):
        category_list_c4.append(1)
    else:
        category_list_c4.append(0)

#train_features_c2 = vectorizer.fit_transform(text_list_c1[:100])

In [43]:
#corpus_filtro5_devset = pandas.read_csv("corpus_filtro5_devset.csv",encoding='utf-8')
#text_devlist_c1=corpus_filtro4median['text'][600:605]
#category_devlist=corpus_filtro5_devset['category'][:]
#test_features_c1 = vectorizer.transform(text_devlist_c1)


In [44]:
nb_c4 = MultinomialNB()
nb_c4.fit(train_features_c1 , category_list_c4[:100])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [45]:
from sklearn.naive_bayes import MultinomialNB
nb_c4.predict_proba(test_features_c1)

array([[  8.50149682e-01,   1.49850318e-01],
       [  9.99410933e-01,   5.89067388e-04],
       [  9.67240543e-01,   3.27594568e-02],
       [  9.53474485e-01,   4.65255154e-02],
       [  9.98839805e-01,   1.16019475e-03]])

In [46]:
nb_c4.predict(test_features_c1)

array([0, 0, 0, 0, 0])

# Clasificador 5 mediana con valor 5 o no

In [47]:
vectorizer_c5 = CountVectorizer(stop_words='english')

In [48]:
#corpus_filtro4median = pandas.read_csv("corpus_filtro4median.csv",encoding='utf-8')
#text_list_c1=corpus_filtro4median['text'][:]
#median_list_c1=corpus_filtro4median['median'][:]
category_list_c5=[]
for i in median_list_c1:
    if(i == 5):
        category_list_c5.append(1)
    else:
        category_list_c5.append(0)

#train_features_c2 = vectorizer.fit_transform(text_list_c1[:100])

In [49]:
#corpus_filtro5_devset = pandas.read_csv("corpus_filtro5_devset.csv",encoding='utf-8')
#text_devlist_c1=corpus_filtro4median['text'][600:605]
#category_devlist=corpus_filtro5_devset['category'][:]
#test_features_c1 = vectorizer.transform(text_devlist_c1)


In [50]:
nb_c5 = MultinomialNB()
nb_c5.fit(train_features_c1 , category_list_c5[:100])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [51]:
from sklearn.naive_bayes import MultinomialNB
nb_c5.predict_proba(test_features_c1)

array([[  9.63672906e-01,   3.63270941e-02],
       [  9.98323905e-01,   1.67609468e-03],
       [  9.98857140e-01,   1.14285986e-03],
       [  9.99772425e-01,   2.27574888e-04],
       [  9.99982259e-01,   1.77407229e-05]])

In [52]:
nb_c5.predict(test_features_c1)

array([0, 0, 0, 0, 0])

# Clasificador 6 mediana con valor 0 o no

In [53]:
vectorizer_c0 = CountVectorizer(stop_words='english')

In [54]:
#corpus_filtro4median = pandas.read_csv("corpus_filtro4median.csv",encoding='utf-8')
#text_list_c1=corpus_filtro4median['text'][:]
#median_list_c1=corpus_filtro4median['median'][:]
category_list_c0=[]
for i in median_list_c1:
    if(i == 0):
        category_list_c0.append(1)
    else:
        category_list_c0.append(0)

#train_features_c2 = vectorizer.fit_transform(text_list_c1[:100])

In [55]:
#corpus_filtro5_devset = pandas.read_csv("corpus_filtro5_devset.csv",encoding='utf-8')
#text_devlist_c1=corpus_filtro4median['text'][600:605]
#category_devlist=corpus_filtro5_devset['category'][:]
#test_features_c1 = vectorizer.transform(text_devlist_c1)


In [56]:
nb_c0 = MultinomialNB()
nb_c0.fit(train_features_c1 , category_list_c0[:100])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [57]:
from sklearn.naive_bayes import MultinomialNB
nb_c0.predict_proba(test_features_c1)

array([[ 0.94489069,  0.05510931],
       [ 0.89388085,  0.10611915],
       [ 0.99840411,  0.00159589],
       [ 0.99685932,  0.00314068],
       [ 0.46576332,  0.53423668]])

In [58]:
nb_c0.predict(test_features_c1)

array([0, 0, 0, 0, 1])

In [59]:
c1_pred=nb_c1.predict_proba(test_features_c1)
c2_pred=nb_c2.predict_proba(test_features_c1)
c3_pred=nb_c3.predict_proba(test_features_c1)
c4_pred=nb_c4.predict_proba(test_features_c1)
c5_pred=nb_c5.predict_proba(test_features_c1)
c0_pred=nb_c0.predict_proba(test_features_c1)

In [63]:
for i in range(5):
    maximum=np.max([c1_pred[i][1],c2_pred[i][1],c3_pred[i][1],c4_pred[i][1],c5_pred[i][1],c0_pred[i][1]])
    if(maximum == c1_pred[i][1]):
        print("Mediana PREDICHA 1")
    elif(maximum == c2_pred[i][1]):
        print("Mediana PREDICHA 2")
    elif(maximum == c3_pred[i][1]):
        print("Mediana PREDICHA 3")
    elif(maximum == c4_pred[i][1]):
        print("Mediana PREDICHA 4")
    elif(maximum == c5_pred[i][1]):
        print("Mediana PREDICHA 5")
    elif(maximum == c0_pred[i][1]):
        print("Mediana PREDICHA 0")


Mediana PREDICHA 3
Mediana PREDICHA 0
Mediana PREDICHA 4
Mediana PREDICHA 3
Mediana PREDICHA 0
